import React,{useEffect,useRef,useState} from 'react';
import {ArrowLeft,Bike,Download,Pause,Play,RotateCcw} from 'lucide-react';
import '@fontsource/dm-sans/400.css';import '@fontsource/dm-sans/500.css';import '@fontsource/dm-sans/600.css';import '@fontsource/dm-sans/700.css';
import '../style.css';import './transitions.css';
import {createTransitionStudy} from './transitions-runtime.js';

const steps={
  Mount:[['Stand beside',0],['Hold & support',.23],['Clear saddle',.46],['Straddle',.70],['Take the seat',.88],['Ready to ride',1]],
  Dismount:[['Stop seated',0],['Plant left foot',.23],['Lift right leg',.34],['Clear saddle',.49],['Land beside',.76],['Stand & release',1]],
};
export default function Transitions(){
  const host=useRef(),engine=useRef();
  const [ready,setReady]=useState(false),[error,setError]=useState(''),[action,setAction]=useState('Dismount'),[phase,setPhase]=useState(0),[playing,setPlaying]=useState(false),[slow,setSlow]=useState(false),[joints,setJoints]=useState(false),[view,setView]=useState('Three-quarter');
  useEffect(()=>{let alive=true;engine.current=createTransitionStudy(host.current,()=>alive&&setReady(true),s=>{if(alive){setPhase(s.phase);setPlaying(s.playing);}},e=>alive&&setError(e.message));return()=>{alive=false;engine.current.dispose();};},[]);
  function select(name){setAction(name);engine.current.action(name);}
  function seek(value){engine.current.seek(Number(value));}
  return <div className="transition-shell"><header className="transition-header"><div className="brand"><Bike size={25}/><h1>Colombo <span>/ Bicycle transitions</span></h1></div><nav aria-label="Study links"><a className="button" href="/assets/cyclist/bicycle-transitions.blend" aria-label="Download Blender file" download><Download size={15}/><span>Blender file</span></a><a className="button" href="/movement.html"><ArrowLeft size={15}/>Courtyard</a></nav></header>
    <main className="transition-workspace"><section className="transition-stage" aria-label="Transition 3D preview"><div className="canvas-host" ref={host}/><div className="transition-caption"><span>MOVEMENT STUDY · 04</span><h2>{action==='Mount'?'Getting on the bicycle':'Getting off the bicycle'}</h2><p>Follow the weight. Keep the contacts.</p></div><div className="transition-views" role="group" aria-label="Camera angle">{['Three-quarter','Side','Front'].map(name=><button className="button" key={name} aria-pressed={view===name} disabled={!ready} onClick={()=>{setView(name);engine.current.view(name);}}>{name}</button>)}</div>
      {(!ready||error)&&<div className="loading-cover"><div className="loading-card"><h2>{error?'Could not load transition study':'Preparing the movement'}</h2><p>{error||'Loading rider, bicycle and animation…'}</p></div></div>}
    </section><aside className="transition-reference"><span className="transition-eyebrow">POSE REFERENCE</span><h2>{action==='Mount'?'Mounting sequence':'Dismounting sequence'}</h2><a href={`/cyclist/references/${action.toLowerCase()}-sequence.png`} target="_blank" rel="noreferrer" aria-label="Open full reference sequence"><img src={`/cyclist/references/${action.toLowerCase()}-sequence.png`} alt={`Six illustrated poses for ${action==='Mount'?'getting on':'getting off'} the bicycle`}/></a><p>Open the sheet to inspect each pose. Scrub the 3D motion below to compare the weight transfer and joint positions.</p><div className="transition-notes"><strong>Contact sequence</strong><p>{action==='Mount'?'Hold the bars → keep the left foot planted → swing the right leg behind the saddle → straddle → sit.':'Move off the seat → plant the left foot → swing the right leg behind the saddle → land → release the bars.'}</p></div></aside></main>
    <section className="transition-controls" aria-label="Transition playback"><div className="transition-toolbar"><div role="group" aria-label="Movement">{['Mount','Dismount'].map(name=><button className="button" key={name} aria-pressed={action===name} disabled={!ready} onClick={()=>select(name)}>{name==='Mount'?'Get on':'Get off'}</button>)}</div><button className="button primary" disabled={!ready} onClick={()=>engine.current.play(!playing)}>{playing?<Pause size={15}/>:<Play size={15}/>} {playing?'Pause':phase>=1?'Replay':'Play'}</button><button className="button" aria-label="Reset movement" disabled={!ready} onClick={()=>seek(0)}><RotateCcw size={15}/></button><button className="button" aria-pressed={slow} disabled={!ready} onClick={()=>{setSlow(!slow);engine.current.slow(!slow);}}>Slow motion</button><button className="button" aria-pressed={joints} disabled={!ready} onClick={()=>{setJoints(!joints);engine.current.joints(!joints);}}>Show joints</button><span className="transition-time">{(phase*3.5).toFixed(2)} / 3.50 s</span></div>
    <label className="transition-timeline">Movement <input type="range" min="0" max="1" step=".001" aria-label="Movement timeline" disabled={!ready} value={phase} onChange={e=>seek(e.target.value)}/><output>{Math.round(phase*100)}%</output></label><div className="transition-steps">{steps[action].map(([label,p])=><button key={label} disabled={!ready} onClick={()=>seek(p)}>{label}</button>)}</div><p className="transition-help">Drag to orbit · Scroll to zoom · Playback stops at the final pose</p></section></div>;
}
