export const assetFiles = [
  {file:'colombo-roads.glb', label:'Full district', kind:'3D model'},
  {file:'road-surfaces.glb', label:'Road surfaces', kind:'3D model'},
  {file:'Colombo_Roads_v1.blend', label:'Editable Blender scene', kind:'Blender'},
  {file:'road-network.json', label:'Road network & controls', kind:'Data'},
  {file:'roads.geojson', label:'Geographic road lines', kind:'Data'},
  {file:'manifest.json', label:'Asset manifest', kind:'Data'},
  {file:'README.md', label:'Asset handover', kind:'Documentation'},
  {file:'source/osm.json', label:'Original OpenStreetMap extract', kind:'Source'},
  {file:'source/context.json', label:'Terrain & building context', kind:'Source'},
  {file:'source/lotus-tower-original.glb', label:'Original Lotus Tower', kind:'Source'},
  {file:'source/config.json', label:'Extent & source query', kind:'Source'},
  {file:'source/prepared-scene.json', label:'Prepared geometry', kind:'Source'},
  {file:'scripts/prepare_asset.py', label:'Data preparation script', kind:'Source'},
  {file:'scripts/build_asset.py', label:'Blender build script', kind:'Source'},
  {file:'cyclist/colombo-cyclist.blend', label:'Cyclist animation in Blender', kind:'Blender'},
  {file:'cyclist/bicycle-fitted.blend', label:'Fitted bicycle in Blender', kind:'Blender'},
  {file:'cyclist/README.md', label:'Cyclist asset notes', kind:'Documentation'},
  {file:'cyclist/courier-movement.blend', label:'Walking and mounting animations', kind:'Blender'},
  {file:'cyclist/bicycle-transitions.blend', label:'Bicycle transition study in Blender', kind:'Blender'},
  {file:'cyclist/TRANSITIONS.md', label:'Mounting and dismounting study', kind:'Documentation'},
  {file:'cyclist/MOVEMENT.md', label:'Walking and riding notes', kind:'Documentation'},
];
