import * as THREE from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {GLTFLoader} from 'three/addons/loaders/GLTFLoader.js';
import {architecturePlacements,cameraPresets,deliveryStops,landscapePlacements,pathLightPlacements} from './layout.js';
import {automaticPhase,phaseState,shouldAnimate} from './environment.js';
import {buildWorldRegistry,trafficDefinitions,validateRegistry} from './worldRegistry.js';
import {createTrafficState,stepTraffic,trafficSnapshot} from './traffic.js';
import {createGround as createPreservedGround,groundRegistryRecords} from './ground.js';
import {attachWind as attachPreservedWind,setWindTime} from './wind.js';
import {applyPedaling as applyRigPedaling,createPedalingRig} from './trafficRig.js';
import {requiredLoadsReady,shouldScheduleFrame} from './runtimePolicy.js';

const assetRoot='/streets/composition';
const BICYCLE_WHEEL_TO_CRANK_RATIO=2.4;

const semantic=(object,id,kind,assetId)=>{object.userData={...object.userData,stableId:id,instanceId:id,kind,prefabAssetId:assetId};return object;};
const entries=manifest=>new Map((manifest.prefabs||manifest.families||manifest.assets||[]).map(entry=>[entry.name||entry.nodeName||entry.node||entry.id,entry]));
function material(resources,options){const value=new THREE.MeshStandardMaterial(options);resources.add(value);return value;}
async function kit(type,placements,resources,windStates){const [response,gltf]=await Promise.all([fetch(`${assetRoot}/${type}.manifest.json`),new GLTFLoader().loadAsync(`${assetRoot}/${type}.glb`)]);if(!response.ok){disposeTree(gltf.scene);throw new Error(type+" manifest returned "+response.status)};const manifest=await response.json(),catalog=entries(manifest),group=semantic(new THREE.Group(),`kit:${type}`,'kit',`kit:${type}`),warnings=[],grouped=new Map();for(const item of placements){if(!grouped.has(item.prefab))grouped.set(item.prefab,[]);grouped.get(item.prefab).push(item);}gltf.scene.updateMatrixWorld(true);const p=new THREE.Vector3(),q=new THREE.Quaternion(),s=new THREE.Vector3(),up=new THREE.Vector3(0,1,0),placement=new THREE.Matrix4(),relative=new THREE.Matrix4(),inverse=new THREE.Matrix4();for(const [prefab,items] of grouped){const entry=catalog.get(prefab),source=gltf.scene.getObjectByName(entry?.node||entry?.nodeName||prefab);if(!source){disposeTree(group);disposeTree(gltf.scene);throw new Error(`${prefab} missing from ${type}`);}source.updateWorldMatrix(true,true);if(prefab==='StreetLamp_Civic'){const lensBounds=new THREE.Box3();source.traverse(object=>{if(object.isMesh&&(Array.isArray(object.material)?object.material:[object.material]).some(mat=>mat.name==='LampLens_Warm'))lensBounds.expandByObject(object);});const lensCenter=lensBounds.getCenter(new THREE.Vector3());source.worldToLocal(lensCenter);group.userData.civicLensLocal=lensCenter.toArray();}inverse.copy(source.matrixWorld).invert();let part=0;source.traverse(object=>{if(!object.isMesh)return;relative.multiplyMatrices(inverse,object.matrixWorld);const batch=semantic(new THREE.InstancedMesh(object.geometry,object.material,items.length),`batch:${type}:${prefab}:${part++}`,`${type}-batch`,entry.assetId||entry.id||`${type}:${prefab}`);batch.userData.instanceIdByIndex=items.map(item=>item.id);batch.castShadow=batch.receiveShadow=true;items.forEach((item,index)=>{p.fromArray(item.position);q.setFromAxisAngle(up,item.yaw||0);s.setScalar(item.scale||1);placement.compose(p,q,s).multiply(relative);batch.setMatrixAt(index,placement);});batch.instanceMatrix.needsUpdate=true;attachPreservedWind(batch,entry,resources,windStates);group.add(batch);});}return {group,warnings,catalog};}
async function landmark(){const gltf=await new GLTFLoader().loadAsync(`${assetRoot}/landmark-lod.glb`),root=semantic(gltf.scene,'landmark:lotus-tower','landmark','landmark:lotus-tower-lod');root.position.set(680,0,-880);root.rotation.y=-.22;return root;}
async function loadTraffic(){
  const [response,gltf]=await Promise.all([
    fetch(`${assetRoot}/traffic.manifest.json`),
    new GLTFLoader().loadAsync(`${assetRoot}/traffic.glb`),
  ]);
  if(!response.ok){disposeTree(gltf.scene);throw new Error("traffic manifest returned "+response.status)};
  const catalog=entries(await response.json());
  const group=semantic(new THREE.Group(),'traffic:corridor','traffic-group','traffic:ambient-corridor');
  const actors=[];
  for(const state of createTrafficState(trafficDefinitions)){
    const entry=catalog.get(state.prefab);
    const source=gltf.scene.getObjectByName(entry?.node||entry?.nodeName||state.prefab);
    if(!source){disposeTree(group);disposeTree(gltf.scene);throw new Error(state.prefab+" missing from traffic")};
    const root=semantic(source.clone(true),state.id,'traffic',entry.assetId||state.prefabAssetId);
    const pivotNames=new Set((entry.motion?.wheelNodes||[]).filter(name=>/__Wheel_(FL|FR|RL|RR|Front|Rear)$/.test(name)));
    const pivots=[];
    root.position.set(state.x,0,state.z);
    root.rotation.y=state.lane==='eastbound'?Math.PI/2:-Math.PI/2;
    root.traverse(object=>{
      if(pivotNames.has(object.name))pivots.push(object);
      if(object.isMesh)for(const mat of Array.isArray(object.material)?object.material:[object.material]){
        if(/headlight/i.test(mat.name)){mat.userData.headlight=true;mat.emissive=new THREE.Color(0xfff0c2);}
      }
    });
    const pedalingRig=createPedalingRig(root,entry.motion);
    group.add(root);actors.push({state,root,pivots,pedalingRig});
  }
  return {group,actors};
}
function pathLights(scene,resources){const body=material(resources,{color:0x273739,roughness:.68}),lens=material(resources,{color:0xffd7a0,emissive:0xffb35f,emissiveIntensity:0}),bodyGeo=new THREE.CylinderGeometry(.095,.13,.62,8),capGeo=new THREE.CylinderGeometry(.12,.12,.1,8),values=[];for(const item of pathLightPlacements){const root=semantic(new THREE.Group(),item.id,'path-light','runtime:path-light-bollard'),a=new THREE.Mesh(bodyGeo,body),b=new THREE.Mesh(capGeo,lens);root.position.set(...item.position);a.position.y=.31;b.position.y=.67;root.add(a,b);scene.add(root);values.push({root,lens});}resources.add(bodyGeo);resources.add(capGeo);return values;}
function positionCivicLights(lights,local){
  if(!local)return;
  for(const light of lights){
    const {item}=light,scale=item.scale||1,yaw=item.yaw||0,c=Math.cos(yaw),s=Math.sin(yaw);
    light.root.position.set(item.position[0]+(local[0]*c+local[2]*s)*scale,item.position[1]+local[1]*scale,item.position[2]+(-local[0]*s+local[2]*c)*scale);
    light.height=light.root.position.y;
  }
}
function disposeTree(root){root?.traverse?.(object=>{object.geometry?.dispose?.();for(const mat of object.material?(Array.isArray(object.material)?object.material:[object.material]):[]){for(const value of Object.values(mat))value?.isTexture&&value.dispose();mat.dispose?.();}});}
function disposeLoadedResults(results){
  for(const result of results){
    if(result.status!=='fulfilled')continue;
    disposeTree(result.value?.group||result.value);
  }
}

export function createCompositionViewer(container,{onStatus,onPreset,onTour,onError,onStats,onRegistry,onPhase}={}){let alive=true,frame=0,touring=false,tourStart=0,tourElapsed=0,activePreset='Garden',loadedState='loading',visible=!document.hidden,motion=true,trafficOn=true,windOn=true,automatic=false,phase='Day',last=performance.now(),elapsed=0;const resources=new Set(),windStates=new Set(),actors=[],scene=new THREE.Scene(),renderer=new THREE.WebGLRenderer({antialias:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio||1,1.6));renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.shadowMap.enabled=true;container.appendChild(renderer.domElement);const camera=new THREE.PerspectiveCamera(45,1,.15,1500),controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.dampingFactor=.08;controls.maxPolarAngle=Math.PI*.48;controls.target.set(...cameraPresets.Garden.target);camera.position.set(...cameraPresets.Garden.position);const hemi=new THREE.HemisphereLight(0xdcebf2,0x607059,1.35),sun=new THREE.DirectionalLight(0xffd9aa,3.15);sun.position.set(-42,68,38);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);sun.shadow.camera.left=-105;sun.shadow.camera.right=105;sun.shadow.camera.top=65;sun.shadow.camera.bottom=-65;const preservedGround=createPreservedGround(resources);const registry=buildWorldRegistry({groundRecords:groundRegistryRecords(preservedGround)});const validation=validateRegistry(registry);scene.add(hemi,sun,sun.target,preservedGround);const trafficGroup=semantic(new THREE.Group(),'traffic:corridor','traffic-group','traffic:ambient-corridor');scene.add(trafficGroup);const lamps=pathLights(scene,resources),civicLamps=landscapePlacements.filter(item=>item.prefab==='StreetLamp_Civic').map(item=>({item,root:{position:new THREE.Vector3(...item.position)},height:5})),pool=Array.from({length:5},()=>{const light=new THREE.PointLight(0xffbd72,0,15,2);scene.add(light);return light;}),marker=semantic(new THREE.Mesh(new THREE.RingGeometry(.32,.48,24),new THREE.MeshBasicMaterial({color:0xffc35a,side:THREE.DoubleSide})),'ui:selected-stop','ui-marker','procedural:stop-marker');marker.rotation.x=-Math.PI/2;marker.visible=false;scene.add(marker);
  function updatePool(on=phaseState(phase).lights){const nearest=[...lamps,...civicLamps].sort((a,b)=>a.root.position.distanceToSquared(camera.position)-b.root.position.distanceToSquared(camera.position)).slice(0,pool.length);pool.forEach((light,i)=>{light.intensity=on?(nearest[i].height>1?72:4.5):0;light.position.set(nearest[i].root.position.x,nearest[i].height||.7,nearest[i].root.position.z);});}
  function setPhase(name){phase=phaseState(name).name;onPhase?.(phase);const state=phaseState(phase);scene.background=new THREE.Color(state.background);scene.fog=new THREE.FogExp2(state.fog,.00135);hemi.intensity=state.hemisphere;sun.intensity=state.sun;renderer.toneMappingExposure=state.exposure;lamps.forEach(item=>item.lens.emissiveIntensity=state.lights?3.2:0);scene.traverse(object=>{if(object.isMesh)for(const mat of Array.isArray(object.material)?object.material:[object.material])if(mat.userData.headlight||/(LampLens_Warm|MAT_Glass)/i.test(mat.name)){mat.emissive?.setHex(mat.userData.headlight?0xfff0c2:0xffb866);mat.emissiveIntensity=state.lights?(mat.userData.headlight?4:1.5):0;}});updatePool(state.lights);invalidate();return phase;}setPhase('Day');
  function invalidate(){if(alive&&!frame)frame=requestAnimationFrame(render);}function render(now){frame=0;if(!alive)return;const delta=Math.min(Math.max((now-last)/1000,0),.05);last=now;const animate=shouldAnimate({visible,motion,reducedMotion:matchMedia('(prefers-reduced-motion: reduce)').matches});if(animate)elapsed+=delta;if(automatic&&animate){const next=automaticPhase(elapsed);if(next!==phase)setPhase(next);}if(touring&&animate){const u=((tourElapsed=(tourElapsed+delta*1000)%38000)/38000),x=-82+u*166;camera.position.set(x,3.1+Math.sin(u*Math.PI)*.6,1.5);controls.target.set(x+25,2.35,u>.62?-4.3:-1.8);}const states=stepTraffic(actors.map(x=>x.state),delta,{paused:!animate||!trafficOn});states.forEach((state,i)=>{const actor=actors[i];actor.contactError=0;const turn=state.wheelAngle-actor.state.wheelAngle;actor.state=state;actor.root.position.x=state.x;actor.pivots.forEach(pivot=>pivot.rotation.x+=turn);actor.contactError=applyRigPedaling(actor.pedalingRig,turn/BICYCLE_WHEEL_TO_CRANK_RATIO);});if(animate&&windOn)setWindTime(windStates,elapsed);controls.update();updatePool();renderer.render(scene,camera);if(shouldScheduleFrame({animate,touring,traffic:trafficOn,wind:windOn,automatic}))invalidate();}
  controls.addEventListener('change',invalidate);controls.addEventListener('start',()=>touring&&setTour(false));const observer=new ResizeObserver(()=>{const w=container.clientWidth,h=container.clientHeight;if(w&&h){camera.aspect=w/h;camera.updateProjectionMatrix();renderer.setSize(w,h,false);invalidate();}});observer.observe(container);const visibility=()=>{visible=!document.hidden;last=performance.now();if(visible)invalidate();};document.addEventListener('visibilitychange',visibility);
  function setTour(value){if(value===touring)return;touring=value;onTour?.(touring);invalidate();}function preset(name){const value=cameraPresets[name];if(!value)return;setTour(false);activePreset=name;camera.position.set(...value.position);controls.target.set(...value.target);controls.update();onPreset?.(name);invalidate();}function focusDeliveryStop(id,{showMarker=true}={}){const stop=deliveryStops.find(x=>x.id===id);if(!stop)return false;setTour(false);const [x,y,z]=stop.entrance.position;camera.position.set(x+(z>0?-9:9),4.2,z+(z>0?-9:9));controls.target.set(x,y+1.4,z);marker.position.set(...stop.approach.position);marker.position.y+=.03;marker.visible=showMarker;controls.update();invalidate();return true;}
  Promise.allSettled([kit('architecture',architecturePlacements,resources,windStates),kit('landscape',landscapePlacements,resources,windStates),landmark(),loadTraffic()]).then(results=>{if(!alive){disposeLoadedResults(results);return;}const warnings=[];results.forEach(result=>{if(result.status==='rejected')warnings.push(result.reason?.message||String(result.reason));else warnings.push(...(result.value?.warnings||[]));});if(!requiredLoadsReady(results)){disposeLoadedResults(results);loadedState='error';onError?.(`Required street kit failed. ${warnings.join(' · ')}`);return;}scene.add(results[0].value.group,results[1].value.group);if(results[2].status==='fulfilled')scene.add(results[2].value);positionCivicLights(civicLamps,results[1].value.group.userData.civicLensLocal);trafficGroup.add(...results[3].value.group.children);actors.push(...results[3].value.actors);setPhase(phase);loadedState='ready';onRegistry?.(registry);onStats?.({warnings,registry:validation});onStatus?.(warnings.length?`Living street ready · ${warnings.length} optional asset warning${warnings.length===1?'':'s'}`:'Living street ready');invalidate();});invalidate();
  return {preset,setTour,toggleTour(){setTour(!touring);return touring;},setPhase,setAutomaticDayCycle(v){automatic=!!v;invalidate();return automatic;},setMotion(v){motion=!!v;invalidate();return motion;},setTraffic(v){trafficOn=!!v;trafficGroup.visible=trafficOn;invalidate();return trafficOn;},setWind(v){windOn=!!v;invalidate();return windOn;},focusDeliveryStop,registry(){return registry;},stats(){return {state:loadedState,render:{calls:renderer.info.render.calls,triangles:renderer.info.render.triangles,geometries:renderer.info.memory.geometries,textures:renderer.info.memory.textures},scene:{phase,visible,motion,trafficOn,windOn,automatic,touring},lights:{pool:pool.length,active:pool.filter(x=>x.intensity>0).length,pathLights:lamps.length},motion:{elapsed:+elapsed.toFixed(3),traffic:trafficSnapshot(actors.map(x=>x.state)),windMaterials:[...windStates].filter(x=>x.time).length,riderContactMax:Math.max(0,...actors.map(x=>x.contactError||0))},registry:validation};},dispose(){alive=false;if(frame)cancelAnimationFrame(frame);document.removeEventListener('visibilitychange',visibility);observer.disconnect();controls.dispose();const disposable=new Set(resources);scene.traverse(object=>{if(object.geometry)disposable.add(object.geometry);if(object.customDepthMaterial)disposable.add(object.customDepthMaterial);for(const mat of object.material?(Array.isArray(object.material)?object.material:[object.material]):[])disposable.add(mat);});disposable.forEach(x=>{for(const value of Object.values(x||{}))if(value?.isTexture)disposable.add(value);x?.dispose?.();});sun.shadow.map?.dispose?.();renderer.renderLists.dispose();renderer.dispose();renderer.domElement.remove();scene.clear();}};}
